name: Bug report
description: Report a bug
labels: bug

body:
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
    validations:
      required: true

- type: textarea
  attributes:
    label: Behaviors
    description: "Expected and actual."
    value: "placeholder"
    validations:
      required: true

- type: textarea
  attributes:
    label: Workaround
    value: "placeholder"
    validations:
      required: false

- type: dropdown
  id: device
  attributes:
    label: Device
    options:
    - Windows 11
    - Windows 10
    - Windows 7
    - Other
    validations:
      required: true

- type: dropdown
  id: mod-version
  attributes:
    label: Mod Version
    options:
    - v2.0.0-beta
    - Other
    validations:
      required: true
